//
//  Conversion.h
//  DOT
//
//  Created by Woncheol Heo on 2018. 7. 2..
//  Copyright © 2018년 wisetracker. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "Product.h"
#import "CustomValue.h"

@interface Conversion : NSObject

@property (nonatomic) NSString *keywordCategory;
@property (nonatomic) NSString *keyword;
@property (nonatomic) CustomValue *customValue;
@property (nonatomic) Product *product;
@property (nonatomic) BOOL pushAgreement;
@property (nonatomic) double g1;
@property (nonatomic) double g2;
@property (nonatomic) double g3;
@property (nonatomic) double g4;
@property (nonatomic) double g5;
@property (nonatomic) double g6;
@property (nonatomic) double g7;
@property (nonatomic) double g8;
@property (nonatomic) double g9;
@property (nonatomic) double g10;
@property (nonatomic) double g11;
@property (nonatomic) double g12;
@property (nonatomic) double g13;
@property (nonatomic) double g14;
@property (nonatomic) double g15;
@property (nonatomic) double g16;
@property (nonatomic) double g17;
@property (nonatomic) double g18;
@property (nonatomic) double g19;
@property (nonatomic) double g20;
@property (nonatomic) double g21;
@property (nonatomic) double g22;
@property (nonatomic) double g23;
@property (nonatomic) double g24;
@property (nonatomic) double g25;
@property (nonatomic) double g26;
@property (nonatomic) double g27;
@property (nonatomic) double g28;
@property (nonatomic) double g29;
@property (nonatomic) double g30;
@property (nonatomic) double g31;
@property (nonatomic) double g32;
@property (nonatomic) double g33;
@property (nonatomic) double g34;
@property (nonatomic) double g35;
@property (nonatomic) double g36;
@property (nonatomic) double g37;
@property (nonatomic) double g38;
@property (nonatomic) double g39;
@property (nonatomic) double g40;
@property (nonatomic) double g41;
@property (nonatomic) double g42;
@property (nonatomic) double g43;
@property (nonatomic) double g44;
@property (nonatomic) double g45;
@property (nonatomic) double g46;
@property (nonatomic) double g47;
@property (nonatomic) double g48;
@property (nonatomic) double g49;
@property (nonatomic) double g50;
@property (nonatomic) double g51;
@property (nonatomic) double g52;
@property (nonatomic) double g53;
@property (nonatomic) double g54;
@property (nonatomic) double g55;
@property (nonatomic) double g56;
@property (nonatomic) double g57;
@property (nonatomic) double g58;
@property (nonatomic) double g59;
@property (nonatomic) double g60;
@property (nonatomic) double g61;
@property (nonatomic) double g62;
@property (nonatomic) double g63;
@property (nonatomic) double g64;
@property (nonatomic) double g65;
@property (nonatomic) double g66;
@property (nonatomic) double g67;
@property (nonatomic) double g68;
@property (nonatomic) double g69;
@property (nonatomic) double g70;
@property (nonatomic) double g71;
@property (nonatomic) double g72;
@property (nonatomic) double g73;
@property (nonatomic) double g74;
@property (nonatomic) double g75;
@property (nonatomic) double g76;
@property (nonatomic) double g77;
@property (nonatomic) double g78;
@property (nonatomic) double g79;
@property (nonatomic) double g80;

- (void)setCustomValues:(CustomValue *)customValue;
- (void)setMicroConversion:(NSString *)constant value:(double)value;
- (void)setMicroConversion1:(double)value;
- (void)setMicroConversion2:(double)value;
- (void)setMicroConversion3:(double)value;
- (void)setMicroConversion4:(double)value;
- (void)setMicroConversion5:(double)value;
- (void)setMicroConversion6:(double)value;
- (void)setMicroConversion7:(double)value;
- (void)setMicroConversion8:(double)value;
- (void)setMicroConversion9:(double)value;
- (void)setMicroConversion10:(double)value;
- (void)setMicroConversion11:(double)value;
- (void)setMicroConversion12:(double)value;
- (void)setMicroConversion13:(double)value;
- (void)setMicroConversion14:(double)value;
- (void)setMicroConversion15:(double)value;
- (void)setMicroConversion16:(double)value;
- (void)setMicroConversion17:(double)value;
- (void)setMicroConversion18:(double)value;
- (void)setMicroConversion19:(double)value;
- (void)setMicroConversion20:(double)value;
- (void)setMicroConversion21:(double)value;
- (void)setMicroConversion22:(double)value;
- (void)setMicroConversion23:(double)value;
- (void)setMicroConversion24:(double)value;
- (void)setMicroConversion25:(double)value;
- (void)setMicroConversion26:(double)value;
- (void)setMicroConversion27:(double)value;
- (void)setMicroConversion28:(double)value;
- (void)setMicroConversion29:(double)value;
- (void)setMicroConversion30:(double)value;
- (void)setMicroConversion31:(double)value;
- (void)setMicroConversion32:(double)value;
- (void)setMicroConversion33:(double)value;
- (void)setMicroConversion34:(double)value;
- (void)setMicroConversion35:(double)value;
- (void)setMicroConversion36:(double)value;
- (void)setMicroConversion37:(double)value;
- (void)setMicroConversion38:(double)value;
- (void)setMicroConversion39:(double)value;
- (void)setMicroConversion40:(double)value;
- (void)setMicroConversion41:(double)value;
- (void)setMicroConversion42:(double)value;
- (void)setMicroConversion43:(double)value;
- (void)setMicroConversion44:(double)value;
- (void)setMicroConversion45:(double)value;
- (void)setMicroConversion46:(double)value;
- (void)setMicroConversion47:(double)value;
- (void)setMicroConversion48:(double)value;
- (void)setMicroConversion49:(double)value;
- (void)setMicroConversion50:(double)value;
- (void)setMicroConversion51:(double)value;
- (void)setMicroConversion52:(double)value;
- (void)setMicroConversion53:(double)value;
- (void)setMicroConversion54:(double)value;
- (void)setMicroConversion55:(double)value;
- (void)setMicroConversion56:(double)value;
- (void)setMicroConversion57:(double)value;
- (void)setMicroConversion58:(double)value;
- (void)setMicroConversion59:(double)value;
- (void)setMicroConversion60:(double)value;
- (void)setMicroConversion61:(double)value;
- (void)setMicroConversion62:(double)value;
- (void)setMicroConversion63:(double)value;
- (void)setMicroConversion64:(double)value;
- (void)setMicroConversion65:(double)value;
- (void)setMicroConversion66:(double)value;
- (void)setMicroConversion67:(double)value;
- (void)setMicroConversion68:(double)value;
- (void)setMicroConversion69:(double)value;
- (void)setMicroConversion70:(double)value;
- (void)setMicroConversion71:(double)value;
- (void)setMicroConversion72:(double)value;
- (void)setMicroConversion73:(double)value;
- (void)setMicroConversion74:(double)value;
- (void)setMicroConversion75:(double)value;
- (void)setMicroConversion76:(double)value;
- (void)setMicroConversion77:(double)value;
- (void)setMicroConversion78:(double)value;
- (void)setMicroConversion79:(double)value;
- (void)setMicroConversion80:(double)value;
@end

